plugins {
    id "maven-publish"
    alias(libs.plugins.shadow)
}

architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    accessWidenerPath = project(":visor-api").file("src/main/resources/visor.accesswidener")
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin because we don't want IDEA to index this.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}
version = version+"-api_fabric"
dependencies {
    compileOnly(project(path: ':visor-api', configuration: 'namedElements'))

    shadowCommon(project(path: ":visor-api", configuration: "namedElements")) { transitive false }
    common(project(path: ":visor-api", configuration: "namedElements")) { transitive false }




    modImplementation(libs.fabric.loader)


    modApi(libs.architectury.lib) { exclude group: "net.fabricmc" exclude group: "net.fabricmc.fabric-api" }


    // ---- LOCAL DEPENDENCY
    shadowCommon(modApi(name: 'atumvr-api-quest')) { transitive = false }
    shadowCommon(modApi(name: 'atumvr-core-quest')) { transitive = false }
    // ----
    //shadowCommon(libs.atumvr.api) { transitive = false }
    //shadowCommon(libs.atumvr.core) { transitive = false }
    shadowCommon(libs.atumvr.config)


}

processResources {
    inputs.property "version", parent.version

    filesMatching("fabric.mod.json") {
        expand "version": parent.version
    }
}


shadowJar {
    exclude "architectury.common.json"
    exclude "org.joml"
    exclude "org.lwjgl"
    exclude "org.slf4j"

    duplicatesStrategy DuplicatesStrategy.EXCLUDE
    configurations = [
            project.configurations.shadowCommon
    ]
    archiveClassifier.set("dev")

    relocate("org.yaml","${project.group}.libs.org.yaml")
    relocate("org.tomlj","${project.group}.libs.org.tomlj")
    relocate("org.checkerframework","${project.group}.libs.org.checkerframework")
    relocate("org.antlr","${project.group}.libs.org.antlr")

    relocate("com.google.gson","${project.group}.libs.com.google.gson")
    relocate("redempt.crunch","${project.group}.libs.redempt.crunch")

}

remapJar {
    injectAccessWidener = true
    input.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier.set('')
}

sourcesJar {
    def commonSources = project(":visor-api").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
